id: P004370
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 11:15:51.664839
source_metadata:
  id: bdr:W1KG9609
  title: ཁྲོས་མའི་སྒྲུབ་སྐོར།
  author: ''
  volumes:
    5a3b4742002c488ea56573adb6336e44:
      image_group_id: I1KG9684
      title: ''
      volume_number: 1
      total_pages: 474
      base_file: v001.txt
    8dcd96f8db7142249fcd4671c7a8972b:
      image_group_id: I1KG9685
      title: ''
      volume_number: 2
      total_pages: 470
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
