id: IDBA6F366
legacy_id: P004370
ocr_import_info:
  bdrc_scan_id: W1KG9609
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T08:12:53'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T18:35:30.611704+00:00'
last_modified: 2022-09-01 02:36:02.423502
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG9609
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG9609
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཁྲོས་མའི་སྒྲུབ་སྐོར།
  author: བདུད་འཇོམས་གླིང་པ།
statistics:
  ocr_word_mean_confidence_index: 0.46872013363168846
  ocr_word_median_confidence_index: 0.3499999940395355
quality: null
bases:
  I1KG9684:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9684
      total_pages: 474
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG9684.txt
    statistics:
      ocr_word_median_confidence_index: 0.3499999940395355
      ocr_word_mean_confidence_index: 0.4700721885269965
    legacy_id: v001
  I1KG9685:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9685
      total_pages: 470
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG9685.txt
    statistics:
      ocr_word_median_confidence_index: 0.3499999940395355
      ocr_word_mean_confidence_index: 0.4671581691844095
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
