id: IDBA6F366
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T08:16:01+00:00'
last_modified: '2022-06-07T22:22:04.632096+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9609
  title: ཁྲོས་མའི་སྒྲུབ་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    43B7:
      image_group_id: I1KG9684
      title: ''
      total_pages: 474
      order: 1
      base_file: 43B7.txt
    A71B:
      image_group_id: I1KG9685
      title: ''
      total_pages: 470
      order: 2
      base_file: A71B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
